import { useEffect, useState } from 'react'
import { approveRecovery, getAtRiskTransactions, getCustomers, getRecoveryAttempts, getRecoverySummary, rejectRecovery } from '../services/api'
import { useApi } from '../hooks/useApi'
import StatCard from '../components/StatCard'
import TransactionTable from '../components/TransactionTable'
import LoadingState from '../components/LoadingState'
import ErrorState from '../components/ErrorState'
import EmptyState from '../components/EmptyState'

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(value || 0)
export default function RecoveryCenter() { const summary=useApi(getRecoverySummary, [], { immediate: false }); const pending=useApi(()=>getRecoveryAttempts({limit:100,offset:0}), [], { immediate: false }); const atRisk=useApi(()=>getAtRiskTransactions({limit:25,offset:0}), [], { immediate: false }); const customers=useApi(()=>getCustomers({limit:500,offset:0})); const [message,setMessage]=useState(''); const refresh=()=>{ summary.run().catch(()=>{}); pending.run().catch(()=>{}); atRisk.run().catch(()=>{}) }; useEffect(()=>{ refresh() },[]); const approvals=(pending.data||[]).filter((item)=>item.status==='PENDING'); const review=async(id, action)=>{ try { if(action==='approve') await approveRecovery(id); else await rejectRecovery(id); setMessage(`Approval ${action}d.`); refresh() } catch(error){ setMessage(error.response?.data?.detail || 'Approval request failed.') } }; const data=summary.data||{}; return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Bounded operations</span><h2>Recovery Center</h2><p className="page-subtitle">Review and execute bounded recovery actions.</p></div></section><div className="kpi-grid kpi-four"><StatCard label="Revenue at risk" value={money(data.current_revenue_at_risk ?? data.revenue_at_risk)} tone="orange"/><StatCard label="Pending approvals" value={data.pending_approvals||0} tone="purple"/><StatCard label="Recovery attempts" value={data.recovery_attempts||0} tone="blue"/><StatCard label="Successful recoveries" value={data.successful_recoveries||0} tone="green"/></div>{message&&<div className="notice">{message}</div>}<section className="panel"><div className="panel-heading"><div><span className="eyebrow">Human review queue</span><h3>Pending human approvals</h3></div></div>{pending.loading?<LoadingState/>:!approvals.length?<EmptyState title="No pending approvals" text="The review queue is clear."/>:<div className="approval-list">{approvals.map((item)=><div className="approval-row" key={item.id}><div><strong>Transaction #{item.transaction_id}</strong><span>{item.action.replaceAll('_',' ')} · {money(item.amount)}</span><small>{item.reason}</small></div><div className="action-row"><button className="button button-primary" onClick={()=>review(item.id,'approve')}>Approve</button><button className="button button-secondary" onClick={()=>review(item.id,'reject')}>Reject</button></div></div>)}</div>}</section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Attention queue</span><h3>At-risk transactions</h3></div></div>{atRisk.loading?<LoadingState/>:atRisk.error?<ErrorState message={atRisk.error}/>:!atRisk.data?.length?<EmptyState/>:<TransactionTable transactions={atRisk.data} customers={Object.fromEntries((customers.data||[]).map((item)=>[item.id,item]))} compact/>}</section></div> }
